name: Merge CI/CD
on: 
    pull_request:
        branches: 
            - main
jobs:
    test:
        name: Test & Deploy
        runs-on: ubuntu-latest
        steps:
        - name: checkout and clone repo
        uses: actions/checkout@v3
        - name: install dependencies
        run: npm i
        - name: run utils-test
        run: npm run utils-test