name: nc-news-workflow
on: [push]
jobs:
  test-deploy:
    name: test-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Use PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
        postgresql db: "my_db"
        postgresql user: "test_user"
        postgresql password: "test_password"
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: PGDATABASE=my_db PGUSER=test_user PGPASSWORD=test_password npm t
